var Arena = 
[[bloody nero", "blue", "chaos", "100", "30", "no", "-", "-"],
["king of oil", "blue", "earth", "100", "30", "yes", "the unknown actor", "-"],
["czarina", "blue", "earth", "100", "30", "no", "-", "-"],
["king Arthur", "blue", "fire", "100", "30", "yes", "dreamer martin", "-"],
["bloody mary", "blue", "fire", "100", "30", "yes", "steam man", "-"],
["silent star", "blue", "lightning", "100", "30", "yes", "bright wizard", "-"],
["dreamer martin", "blue", "lightning", "100", "30", "no", "-", "-"],
["tesla trooper", "blue", "lightning", "100", "30", "no", "-", "-"],
["clonebus", "blue", "water", "100", "30", "yes", "maurya emperor", "-"],
["maurya emperor", "blue", "water", "100", "30", "no", "-", "-"],
["cleopatra", "purple", "fire", "400", "50", "yes", "king Arthur", "pfk"],
["founding father", "purple", "lightning", "400", "50", "no", "-", "-"]]

var Expedition = 
[["great peter", "blue", "earth", "350", "30", "yes", "nobunaga", "-"],
["middle class hero", "blue", "earth", "350", "30", "no", "-", "-"],
["alchemist", "blue", "earth", "350", "30", "no", "-", "-"],
["flying man", "blue", "fire", "350", "30", "no", "-", "-"],
[""che"", "blue", "fire", "350", "30", "no", "-", "-"],
["steam man", "blue", "fire", "350", "30", "no", "-", "-"],
["gali.gary", "blue", "fire", "350", "30", "no", "-", "-"],
["louise xxiv", "blue", "fire", "350", "30", "no", "-", "-"],
["dreamlover", "blue", "lightning", "350", "30", "no", "-", "-"],
["dugout doug", "blue", "lightning", "350", "30", "no", "-", "-"],
["blessed teresa", "blue", "order", "350", "30", "no", "-", "-"],
["uncrowned queen", "blue", "water", "350", "30", "yes", "middle class hero", "-"],
["nobunaga", "blue", "water", "350", "30", "no", "-", "-"],
["master kung", "blue", "water", "350", "30", "no", "-", "-"],
["july.caesar", "purple", "earth", "1500", "50", "yes", "bear huner", "mr.ms"],
["poet william", "purple", "earth", "1500", "50", "yes", "great peter", "d.vixni"],
["symphony.D", "purple", "fire", "1500", "50", "no", "-", "-"],
["kim", "purple", "water", "1500", "50", "yes", "shinzo", "Elizabeth"]]

var Tavern = 
[["Desert Fox", "blue", "chaos", "500", "30", "no", "-", "-"],
["D.Vinxi", "blue", "earth", "500", "30", "yes", "alchemist", "-"],
["Marco", "blue", "earth", "500", "30", "no", "-", "-"],
["iori female", "blue", "earth", "500", "30", "no", "-", "-"],
["the unknown actor", "blue", "earth", "500", "30", "no", "-", "-"],
["Aung San Suki", "blue", "fire", "500", "30", "no", "-", "-"],
["Tanitrus Benjamin", "blue", "lightning", "500", "30", "yes", "dreamlover", "-"],
["Bright Wizard", "blue", "lightning", "500", "30", "no", "-", "-"],
["bell iv", "blue", "lightning", "500", "30", "no", "-", "-"],
["w.wallace", "blue", "order", "500", "30", "no", "-", "-"],
["Archimedes", "blue", "water", "500", "30", "no", "-", "-"],
["shogun I", "blue", "water", "500", "30", "no", "-", "-"],
["Honest Abe", "Purple", "earth", "2000", "50", "yes", "uncrowned queen", "joan"],
["Uncle Joe", "Purple", "water", "2000", "50", "yes", "mulan", "fat chill]]
